apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-cp4d-instance-cp4d-instance
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitops-cp4d-instance
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/gitops-cp4d-instance/cp4d-instance
    repoURL: https://github.com/se-test-sp/swe-local-test
    targetRevision: main
    helm:
      releaseName: cp4d-instance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
