apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: {{ .Values.cp4d_instance_name }}                       # This is the recommended name, but you can change it
  namespace: {{ .Values.cp4d_namespace }}                # Replace with the project where you will install Cloud Pak for Data
spec:
  license:
    accept: {{ .Values.license_accept }} 
    license: {{ .Values.license }} 
  storageVendor: {{ .Values.storage_vendor }} 