apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-common-services-ibm-entitlement-key
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ibm-common-services
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/ibm-common-services/ibm-entitlement-key
    repoURL: https://github.com/se-test-sp/swe-local-test
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
